is-a-dev/register

domains/attaditya.json

I hope this get approved and then I can smile like :D

Attachment Aditya's Web Page :D

---

domains/penguin.json

So i decided to change mail services @phenax could you review this?

Change mail services

---

domains/kunal.json

changing dns for transferring hashnode to railway

---

domains/ahku.json

Register ahku.is-a.dev

---

domains/onvy.json

Register onvy.is-a.dev

---

domains/rhyk.json

Register rhyk.is-a.dev

---

domains/vbkg.json

Register vbkg.is-a.dev

---

domains/ambaskaryash.json

Added `ambaskaryash` via the registration website.

Register ambaskaryash.is-a.dev

---

domains/daflixy.json
domains/valswap.json

Added `daflixy.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

Register daflixy.is-a.dev

---

domains/ariez.json

Add Cloudflare pages CNAME incase ariez.codes expires

---

domains/ariez.json

I replaced ariez-codes.pages.dev with the new one!

---

domains/harsh.json

harsh.json

---

domains/dr-therapy.json
domains/drtherapy.json

Added `drtherapy.is-a.dev` using the site.

BETA: Register drtherapy.is-a.dev

---

domains/hero.json

Added `hero.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register hero.is-a.dev

---

domains/albuman.json

Added `albuman.is-a.dev` using the site.

BETA: Register albuman.is-a.dev

---

domains/hero.json

Updated `hero.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Update hero.is-a.dev

---

domains/tm-math.json

Added `tm-math.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register tm-math.is-a.dev

---

domains/kleb.json

Added `kleb.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register kleb.is-a.dev

---

domains/eternalnetwork.json

Added `eternalnetwork.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register eternalnetwork.is-a.dev

---

domains/yourmom.json

Added `yourmom.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register yourmom.is-a.dev

---

domains/notarya.json

PLEASE SEE Update notarya.json

---

domains/legalise.json

Added `legalise.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register legalise.is-a.dev

---

domains/notarya.json

Added `notarya.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register notarya.is-a.dev

---

domains/arghozali.json

Added `arghozali.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register arghozali.is-a.dev

---

domains/lenn106.json

Added `lenn106.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register lenn106.is-a.dev

---

domains/gauravgupta.json
domains/gauravgupta256.json

Added `gauravgupta.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register gauravgupta.is-a.dev

---

domains/ice-head.json

Added `ice-head.is-a.dev` using the Discord bot.

BETA: Register ice-head.is-a.dev

---

domains/mpangobank.json

Added `mpangobank.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register mpangobank.is-a.dev

---

domains/jkb-bio.json
domains/jtgr.json

Added `jtgr.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register jtgr.is-a.dev

---

domains/bobert.json

Added `bobert.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register bobert.is-a.dev

---

domains/farhan.json

Added `farhan.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register farhan.is-a.dev

---

domains/bni.co.id.json
domains/eform.bni.co.id.json

Added `bni.co.id.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register bni.co.id.is-a.dev

---

domains/lamfun.json
domains/lamger.json
domains/lamgerr.json
domains/lamgerxd.json

Added `lamgerxd.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register lamgerxd.is-a.dev

---

domains/lordwolfy.json

Added `lordwolfy.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register lordwolfy.is-a.dev

---

domains/rain.json

Added `rain.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register rain.is-a.dev

---

domains/johndo.json
domains/komovie.json
domains/komovies.json

Added `johndo.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register johndo.is-a.dev

---

domains/champion.json

Register champion.is-a.dev with CNAME record pointing to immrchampion.github.io.

Register champion.is-a.dev

---

domains/anakhalal.json

Added `anakhalal.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register anakhalal.is-a.dev

---

domains/amodity.json

Added `amodity.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register amodity.is-a.dev

---

domains/victoris.json
domains/victorisgeek.json
domains/yes.json

Added `yes.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register yes.is-a.dev

---

domains/storm.json

Added `storm.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register storm.is-a.dev

---

domains/abdel.json
domains/netsterx.json

Added `netsterx.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register netsterx.is-a.dev

---

domains/abdessattar.json

Added `abdessattar.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register abdessattar.is-a.dev

---

domains/abdelghani.json

Added `abdelghani.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register abdelghani.is-a.dev

---

domains/lh.json

Added `lh.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register lh.is-a.dev

---

domains/sudo.json

Added `sudo.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register sudo.is-a.dev

---

domains/nandhu.json

Added `nandhu.is-a.dev` using the [CLI](https://www.npmjs.com/package/@is-a-dev/cli).

Register nandhu.is-a.dev

---

domains/mrtomxxx.json

Added `mrtomxxx.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register mrtomxxx.is-a.dev

---

domains/exotic.json

Added `exotic.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register exotic.is-a.dev

---

domains/0bun.json
domains/keikibun.json
domains/zerobun.json

Added `0bun.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register 0bun.is-a.dev

---

domains/xiaozhu2007.json

Added `xiaozhu2007.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register xiaozhu2007.is-a.dev

---

domains/huyduc.json

Added `huyduc.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register huyduc.is-a.dev

---

domains/rajuan.json

Added `rajuan.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register rajuan.is-a.dev

---

domains/vikas-mahi.json

Added `vikas-mahi.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register vikas-mahi.is-a.dev

---

domains/hackpig520.json

Added `hackpig520.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register hackpig520.is-a.dev

---

domains/decentparadox.json

Added `decentparadox.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register decentparadox.is-a.dev

---

domains/ians.json

Added `ians.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register ians.is-a.dev

---

domains/plumsy.json

Added `plumsy.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register plumsy.is-a.dev

---

domains/goguardian.json
domains/mosaic.json

Register goguardian.is-a.dev with CNAME record pointing to loooooooooooooooool.onrender.com.

Register goguardian.is-a.dev

---

domains/prime.json

- [ DONE] The file is in the `domains` folder and is in the JSON format.
- [DONE] You have completed your website. 
- [DONE] The website is reachable.  
- [HOSTED ON GITHUB PAGES] You're not using Vercel or Netlify.  
- [NOPE] The CNAME record doesn't contain `https://` or `/`.  
- [ DONE] There is sufficient information at the `owner` field.  
https://primetdmomega.github.io - My personal website hosted with GitHub Pages

REGISTER prime.is-a.dev

---

domains/emmy.json

Added `emmy.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register emmy.is-a.dev

---

domains/ecoplayer.json
domains/ecoplayer07.json

Added `ecoplayer.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register ecoplayer.is-a.dev

---

domains/soumo.json

Added `soumo.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register soumo.is-a.dev

---

domains/lowrp.site.json

Added `lowrp.site.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register lowrp.site.is-a.dev

---

domains/ibrahimai.json
domains/ibrahimtech.json

Added `ibrahimai.is-a.dev` using the [dashboard](https://manage.is-a.dev).

BETA: Register ibrahimai.is-a.dev

---

domains/neca.json

Register neca.is-a.dev with TXT record pointing to zoho-verification=zb18547320.zmverify.zoho.eu.

Register neca.is-a.dev

---

domains/monkey3three.json

Register monkey3three.is-a.dev with CNAME record pointing to portfolio-9xw.pages.dev.

Register monkey3three.is-a.dev

---

domains/_github-pages-challenge-Fluffythebunny.json
domains/fluffythebunny.json

- [✓] The file is in the `domains` folder and is in the JSON format.
- [✓] The file's name is all lowercased and alphanumeric. 
- [✓] You have completed your website. 
- [✓] The website is reachable.  
- [✓] The CNAME record doesn't contain `https://` or `/`.  
- [✓] There is sufficient information at the `owner` field.  
https://fluffythebunny.github.io/fluffythebunny.is-a.dev/

Github pages registration

---

domains/devarnav.json

Updated CNAME record at devarnav.json

---

domains/_vercel.jake.json
domains/jake.json

Register jake.is-a.dev

---

domains/_vercel.v.json
domains/v.json

Register v.is-a.dev

---

domains/_vercel.z.json
domains/z.json

Register my sub domain

---

domains/devarnav.json
domains/zmail._domainkey.devarnav.json

CREATED A SUB-SUB-SUBDOMAIN FOR ZOHO MAIL VERIFY

---

domains/_vercel.works.arnxv.json
domains/works.arnxv.json

[works-gamma-beryl.vercel.app](https://works-gamma-beryl.vercel.app/)

added works subdomain and some records for vercel

---

domains/lyaxsh.json

is-a.dev pr

---

domains/_vercel.whothree.json
domains/whothree.json

vercel website whothree

---

domains/mrdavidss.json

Request of https://mrdavidss.is-a.dev/ .

---

domains/generic.json

Current link: [https://xgeneric.github.io](https://xgeneric.github.io)

Request for the subdomain: generic.is-a.dev

---

domains/sap.json

https://ripangelhacks-github-io.pages.dev/

Fix: Website broke due to making site proxied

---

domains/exphert.json
domains/sans.json

Register sans.is-a.dev and exphert.is-a.dev domain (sans.json and exphert.json)
